= Hello Bot

image:https://travis-ci.org/chatbot-workshop/kotlin-slack-hello.svg?branch=master["Build Status", link="https://travis-ci.org/chatbot-workshop/kotlin-slack-hello"]

**A very simple bot example for https://slack.com/[Slack] written in https://kotlinlang.org/[Kotlin].**

*Copyright (C) 2017 Marcus Fihlon*

This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

== Preparation

. Go to https://my.slack.com/services/new/bot and create a new bot.
. Write down the name of your bot and the auth token.
. Clone this repository: `git clone https://github.com/chatbot-workshop/kotlin-slack-hello.git`

== Configuration

Open the file `src/main/resources/bot.conf` and enter the name of the bot, the auth token and the name of the channel, the bot should listen at in the corresponding lines.

== Running

Run the bot within your IDE or use https://gradle.org/[Gradle] at the command line: `./gradlew run`

== Testing

. Open https://slack.com/[Slack] and login using your credentials
. Go to the channel your bot is listening at
. Send a message directly to your bot (use `@botName` with the name of your bot)
. You should receive an answer saying `Hello, your name` with your name
